name: OTA
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy:
    name: Deploy To OTA
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to OTA
        uses: bravesoft-sinh/ota-action
        env:
          USER: ${{ secrets.USER }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}